[2024-11-28T13:04:37.942+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-28T13:04:38.020+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet manual__2024-11-28T13:04:33.781269+00:00 [queued]>
[2024-11-28T13:04:38.037+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet manual__2024-11-28T13:04:33.781269+00:00 [queued]>
[2024-11-28T13:04:38.046+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-28T13:04:38.073+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_kafka_to_parquet> on 2024-11-28 13:04:33.781269+00:00
[2024-11-28T13:04:38.086+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=7911) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-28T13:04:38.083+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'run_spark_kafka_to_parquet', 'manual__2024-11-28T13:04:33.781269+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpyov0s1yk']
[2024-11-28T13:04:38.088+0000] {standard_task_runner.py:64} INFO - Started process 7912 to run task
[2024-11-28T13:04:38.089+0000] {standard_task_runner.py:91} INFO - Job 78: Subtask run_spark_kafka_to_parquet
[2024-11-28T13:04:38.211+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet manual__2024-11-28T13:04:33.781269+00:00 [running]> on host cc9ad6cea7ef
[2024-11-28T13:04:38.493+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='run_spark_kafka_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T13:04:33.781269+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-28T13:04:33.781269+00:00'
[2024-11-28T13:04:38.496+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-28T13:04:38.542+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-28T13:04:38.546+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', ' \n            # Copier les fichiers nécessaires dans le conteneur spark-master\n            docker cp ./dependencies.zip spark-master:/dependencies.zip\n            docker cp ./dags/kafka_to_parquet.py spark-master:/kafka_to_parquet.py\n        \n            # Exécuter le job Spark avec les fichiers copiés et les packages nécessaires\n            docker exec -it spark-master spark-submit                 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1                 --py-files /dependencies.zip                 /kafka_to_parquet.py\n        ']
[2024-11-28T13:04:38.573+0000] {subprocess.py:86} INFO - Output:
[2024-11-28T13:04:38.626+0000] {subprocess.py:93} INFO - lstat /tmp/***tmp2xdahigc/dependencies.zip: no such file or directory
[2024-11-28T13:04:38.678+0000] {subprocess.py:93} INFO - lstat /tmp/***tmp2xdahigc/dags: no such file or directory
[2024-11-28T13:04:38.724+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-11-28T13:04:38.728+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-28T13:04:38.731+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-28T13:04:38.762+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-28T13:04:38.779+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=run_spark_kafka_to_parquet, run_id=manual__2024-11-28T13:04:33.781269+00:00, execution_date=20241128T130433, start_date=20241128T130438, end_date=20241128T130438
[2024-11-28T13:04:38.830+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 78 for task run_spark_kafka_to_parquet (Bash command failed. The command returned a non-zero exit code 1.; 7912)
[2024-11-28T13:04:38.871+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-28T13:04:38.901+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
