[2024-11-27T21:39:11.207+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T21:39:11.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.fetch_openweathermap_data manual__2024-11-27T21:24:05.735167+00:00 [queued]>
[2024-11-27T21:39:11.293+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.fetch_openweathermap_data manual__2024-11-27T21:24:05.735167+00:00 [queued]>
[2024-11-27T21:39:11.301+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2024-11-27T21:39:11.332+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_openweathermap_data> on 2024-11-27 21:24:05.735167+00:00
[2024-11-27T21:39:11.342+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'fetch_openweathermap_data', 'manual__2024-11-27T21:24:05.735167+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp50j28lh5']
[2024-11-27T21:39:11.346+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask fetch_openweathermap_data
[2024-11-27T21:39:11.349+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1681) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T21:39:11.351+0000] {standard_task_runner.py:64} INFO - Started process 1682 to run task
[2024-11-27T21:39:11.418+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.fetch_openweathermap_data manual__2024-11-27T21:24:05.735167+00:00 [running]> on host cc9ad6cea7ef
[2024-11-27T21:39:11.546+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='fetch_openweathermap_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T21:24:05.735167+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-27T21:24:05.735167+00:00'
[2024-11-27T21:39:11.548+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T21:39:11.812+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.18.0.8', 9093)]>: connecting to kafka:9093 [('172.18.0.8', 9093) IPv4]
[2024-11-27T21:39:11.814+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-11-27T21:39:11.816+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.18.0.8', 9093)]> returned error 111. Disconnecting.
[2024-11-27T21:39:11.816+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.18.0.8', 9093)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-11-27T21:39:11.864+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.18.0.8', 9093)]>: connecting to kafka:9093 [('172.18.0.8', 9093) IPv4]
[2024-11-27T21:39:11.865+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.18.0.8', 9093)]> returned error 111. Disconnecting.
[2024-11-27T21:39:11.866+0000] {conn.py:673} ERROR - <BrokerConnection node_id=bootstrap-0 host=kafka:9093 <connecting> [IPv4 ('172.18.0.8', 9093)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-11-27T21:39:11.867+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T21:39:11.867+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream.py", line 29, in fetch_openweathermap_data
    producer = KafkaProducer(bootstrap_servers=KAFKA_SERVER,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/producer/kafka.py", line 383, in __init__
    client = self.config['kafka_client'](
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 234, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/kafka/client_async.py", line 902, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-11-27T21:39:11.884+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=weather_data_kafka_dag, task_id=fetch_openweathermap_data, run_id=manual__2024-11-27T21:24:05.735167+00:00, execution_date=20241127T212405, start_date=20241127T213911, end_date=20241127T213911
[2024-11-27T21:39:11.906+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task fetch_openweathermap_data (NoBrokersAvailable; 1682)
[2024-11-27T21:39:11.928+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-27T21:39:11.953+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T21:39:11.958+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
