[2024-12-03T20:07:23.580+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T20:07:23.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.copy_openmeteo manual__2024-12-03T20:06:00.526510+00:00 [queued]>
[2024-12-03T20:07:23.648+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.copy_openmeteo manual__2024-12-03T20:06:00.526510+00:00 [queued]>
[2024-12-03T20:07:23.649+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-12-03T20:07:23.671+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): copy_openmeteo> on 2024-12-03 20:06:00.526510+00:00
[2024-12-03T20:07:23.683+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'copy_openmeteo', 'manual__2024-12-03T20:06:00.526510+00:00', '--job-id', '786', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp147ty78h']
[2024-12-03T20:07:23.689+0000] {standard_task_runner.py:91} INFO - Job 786: Subtask copy_openmeteo
[2024-12-03T20:07:23.690+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3436) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T20:07:23.691+0000] {standard_task_runner.py:64} INFO - Started process 3443 to run task
[2024-12-03T20:07:23.757+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.copy_openmeteo manual__2024-12-03T20:06:00.526510+00:00 [running]> on host 0f9edd113eb4
[2024-12-03T20:07:23.889+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='copy_openmeteo' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T20:06:00.526510+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T20:06:00.526510+00:00'
[2024-12-03T20:07:23.892+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T20:07:23.914+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-03T20:07:23.915+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker cp ./data/parquet_files/openmeteo_data.parquet spark-master:/openmeteo_data.parquet']
[2024-12-03T20:07:23.928+0000] {subprocess.py:86} INFO - Output:
[2024-12-03T20:07:23.971+0000] {subprocess.py:93} INFO - lstat /tmp/***tmp1uri68r1/data: no such file or directory
[2024-12-03T20:07:23.976+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-03T20:07:23.977+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T20:07:23.992+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-03T20:07:23.999+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=copy_openmeteo, run_id=manual__2024-12-03T20:06:00.526510+00:00, execution_date=20241203T200600, start_date=20241203T200723, end_date=20241203T200723
[2024-12-03T20:07:24.018+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 786 for task copy_openmeteo (Bash command failed. The command returned a non-zero exit code 1.; 3443)
[2024-12-03T20:07:24.065+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-12-03T20:07:24.104+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T20:07:24.107+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
