[2024-12-03T11:49:57.192+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T11:49:57.217+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.docker_cp_and_spark_submit manual__2024-12-03T11:49:19.653568+00:00 [queued]>
[2024-12-03T11:49:57.225+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.docker_cp_and_spark_submit manual__2024-12-03T11:49:19.653568+00:00 [queued]>
[2024-12-03T11:49:57.226+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-12-03T11:49:57.239+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): docker_cp_and_spark_submit> on 2024-12-03 11:49:19.653568+00:00
[2024-12-03T11:49:57.246+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'docker_cp_and_spark_submit', 'manual__2024-12-03T11:49:19.653568+00:00', '--job-id', '653', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpjtzj4pe7']
[2024-12-03T11:49:57.248+0000] {standard_task_runner.py:91} INFO - Job 653: Subtask docker_cp_and_spark_submit
[2024-12-03T11:49:57.248+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1606) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T11:49:57.248+0000] {standard_task_runner.py:64} INFO - Started process 1608 to run task
[2024-12-03T11:49:57.285+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.docker_cp_and_spark_submit manual__2024-12-03T11:49:19.653568+00:00 [running]> on host 0741a2a1545f
[2024-12-03T11:49:57.327+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'docker_cp_and_spark_submit', field 'bash_command'. Template: './script/docker_task.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./script/docker_task.sh
[2024-12-03T11:49:57.333+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./script/docker_task.sh
[2024-12-03T11:49:57.340+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=docker_cp_and_spark_submit, run_id=manual__2024-12-03T11:49:19.653568+00:00, execution_date=20241203T114919, start_date=20241203T114957, end_date=20241203T114957
[2024-12-03T11:49:57.350+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 653 for task docker_cp_and_spark_submit (./script/docker_task.sh; 1608)
[2024-12-03T11:49:57.382+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-12-03T11:49:57.399+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T11:49:57.404+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
