[2024-11-28T12:38:10.815+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-28T12:38:10.940+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-28T11:00:00+00:00 [queued]>
[2024-11-28T12:38:10.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-28T11:00:00+00:00 [queued]>
[2024-11-28T12:38:10.974+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-28T12:38:11.021+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_kafka_to_parquet> on 2024-11-28 11:00:00+00:00
[2024-11-28T12:38:11.041+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'run_spark_kafka_to_parquet', 'scheduled__2024-11-28T11:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpdqbs1tx7']
[2024-11-28T12:38:11.048+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=6407) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-28T12:38:11.050+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask run_spark_kafka_to_parquet
[2024-11-28T12:38:11.051+0000] {standard_task_runner.py:64} INFO - Started process 6412 to run task
[2024-11-28T12:38:11.197+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-28T11:00:00+00:00 [running]> on host cc9ad6cea7ef
[2024-11-28T12:38:11.481+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='run_spark_kafka_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T11:00:00+00:00'
[2024-11-28T12:38:11.483+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-28T12:38:11.508+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-28T12:38:11.510+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            # Copier les fichiers nécessaires dans le conteneur spark-master\n            docker cp ./dependencies.zip spark-master:/dependencies.zip\n            docker cp ./dags/kafka_to_parquet.py spark-master:/kafka_to_parquet.py\n        \n            # Exécuter le job Spark avec les fichiers copiés et les packages nécessaires\n            docker exec -it spark-master spark-submit                 --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1                 --py-files /dependencies.zip                 /kafka_to_parquet.py\n        ']
[2024-11-28T12:38:11.525+0000] {subprocess.py:86} INFO - Output:
[2024-11-28T12:38:11.594+0000] {subprocess.py:93} INFO - lstat /tmp/***tmp5yqf_h5y/dependencies.zip: no such file or directory
[2024-11-28T12:38:11.626+0000] {subprocess.py:93} INFO - lstat /tmp/***tmp5yqf_h5y/dags: no such file or directory
[2024-11-28T12:38:11.684+0000] {subprocess.py:93} INFO - Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2024-11-28T12:38:11.701+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-11-28T12:38:11.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-28T12:38:11.727+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-11-28T12:38:11.747+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=run_spark_kafka_to_parquet, run_id=scheduled__2024-11-28T11:00:00+00:00, execution_date=20241128T110000, start_date=20241128T123810, end_date=20241128T123811
[2024-11-28T12:38:11.803+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task run_spark_kafka_to_parquet (Bash command failed. The command returned a non-zero exit code 1.; 6412)
[2024-11-28T12:38:11.837+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-28T12:38:11.905+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-28T12:38:11.931+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
