[2024-11-27T23:02:09.216+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T23:02:09.300+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-27T22:00:00+00:00 [queued]>
[2024-11-27T23:02:09.320+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-27T22:00:00+00:00 [queued]>
[2024-11-27T23:02:09.328+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-27T23:02:09.364+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_kafka_to_parquet> on 2024-11-27 22:00:00+00:00
[2024-11-27T23:02:09.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'run_spark_kafka_to_parquet', 'scheduled__2024-11-27T22:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpcasmyszt']
[2024-11-27T23:02:09.381+0000] {standard_task_runner.py:91} INFO - Job 29: Subtask run_spark_kafka_to_parquet
[2024-11-27T23:02:09.383+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=3897) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T23:02:09.384+0000] {standard_task_runner.py:64} INFO - Started process 3898 to run task
[2024-11-27T23:02:09.471+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-27T22:00:00+00:00 [running]> on host cc9ad6cea7ef
[2024-11-27T23:02:09.644+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='run_spark_kafka_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-27T22:00:00+00:00'
[2024-11-27T23:02:09.645+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T23:02:09.682+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-27T23:02:09.684+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit ./kafka_to_parquet.py']
[2024-11-27T23:02:09.695+0000] {subprocess.py:86} INFO - Output:
[2024-11-27T23:02:09.703+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: spark-submit: command not found
[2024-11-27T23:02:09.704+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-27T23:02:09.706+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T23:02:09.729+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-27T23:02:09.740+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=run_spark_kafka_to_parquet, run_id=scheduled__2024-11-27T22:00:00+00:00, execution_date=20241127T220000, start_date=20241127T230209, end_date=20241127T230209
[2024-11-27T23:02:09.767+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 29 for task run_spark_kafka_to_parquet (Bash command failed. The command returned a non-zero exit code 127.; 3898)
[2024-11-27T23:02:09.804+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-27T23:02:09.837+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T23:02:09.842+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-11-27T23:14:37.782+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-27T23:14:37.815+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-27T22:00:00+00:00 [queued]>
[2024-11-27T23:14:37.824+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-27T22:00:00+00:00 [queued]>
[2024-11-27T23:14:37.825+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-27T23:14:37.840+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_kafka_to_parquet> on 2024-11-27 22:00:00+00:00
[2024-11-27T23:14:37.848+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4381) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-27T23:14:37.846+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'run_spark_kafka_to_parquet', 'scheduled__2024-11-27T22:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpa1jg7y1z']
[2024-11-27T23:14:37.849+0000] {standard_task_runner.py:64} INFO - Started process 4382 to run task
[2024-11-27T23:14:37.849+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask run_spark_kafka_to_parquet
[2024-11-27T23:14:37.894+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.run_spark_kafka_to_parquet scheduled__2024-11-27T22:00:00+00:00 [running]> on host cc9ad6cea7ef
[2024-11-27T23:14:37.978+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='run_spark_kafka_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T22:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-27T22:00:00+00:00'
[2024-11-27T23:14:37.979+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-27T23:14:37.990+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-27T23:14:37.992+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit ./kafka_to_parquet.py']
[2024-11-27T23:14:37.999+0000] {subprocess.py:86} INFO - Output:
[2024-11-27T23:14:38.001+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: spark-submit: command not found
[2024-11-27T23:14:38.001+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-11-27T23:14:38.002+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-27T23:14:38.010+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-11-27T23:14:38.014+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=run_spark_kafka_to_parquet, run_id=scheduled__2024-11-27T22:00:00+00:00, execution_date=20241127T220000, start_date=20241127T231437, end_date=20241127T231438
[2024-11-27T23:14:38.027+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 35 for task run_spark_kafka_to_parquet (Bash command failed. The command returned a non-zero exit code 127.; 4382)
[2024-11-27T23:14:38.063+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-27T23:14:38.079+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-27T23:14:38.083+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
