[2024-11-28T22:13:31.573+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-28T22:13:31.667+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-28T21:00:00+00:00 [queued]>
[2024-11-28T22:13:31.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-28T21:00:00+00:00 [queued]>
[2024-11-28T22:13:31.690+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2024-11-28T22:13:31.723+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_openweathermap_data> on 2024-11-28 21:00:00+00:00
[2024-11-28T22:13:31.736+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'store_openweathermap_data', 'scheduled__2024-11-28T21:00:00+00:00', '--job-id', '220', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp0x0h9dkd']
[2024-11-28T22:13:31.740+0000] {standard_task_runner.py:91} INFO - Job 220: Subtask store_openweathermap_data
[2024-11-28T22:13:31.746+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=899) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-28T22:13:31.748+0000] {standard_task_runner.py:64} INFO - Started process 909 to run task
[2024-11-28T22:13:31.832+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-28T21:00:00+00:00 [running]> on host 0741a2a1545f
[2024-11-28T22:13:32.054+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='store_openweathermap_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-28T21:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-28T21:00:00+00:00'
[2024-11-28T22:13:32.060+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-28T22:13:32.099+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-28T22:13:32.100+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kafka_stream.py", line 146, in store_openweathermap_data
    read_from_kafka_and_store(KAFKA_TOPIC_OPENWEATHER, "openweathermap_data.parquet")
  File "/opt/airflow/dags/kafka_stream.py", line 141, in read_from_kafka_and_store
    logging.error(f"Error reading from Kafka topic {topic_name}: {e}")
                                                                  ^
NameError: name 'e' is not defined
[2024-11-28T22:13:32.127+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=store_openweathermap_data, run_id=scheduled__2024-11-28T21:00:00+00:00, execution_date=20241128T210000, start_date=20241128T221331, end_date=20241128T221332
[2024-11-28T22:13:32.152+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 220 for task store_openweathermap_data (name 'e' is not defined; 909)
[2024-11-28T22:13:32.204+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-28T22:13:32.221+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
